name: update_epic

on:
  schedule:
    - cron: '0 14 1/3 * *'
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: CHECKOUT
      run: |
        git clone -b master https://github.com/luminoleon/epicgames-claimer.git
        cd epicgames-claimer
        pip3 install -r requirements.txt
        sudo sh install_dependencies.sh
        python main.py -o -u ${{ secrets.UN }} -p ${{ secrets.PW }}
        
    - name: Telegram Notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TG_BOT_TOKEN }} #use bot @BotFather
        chatId: ${{ secrets.TG_CHAT_ID }} #use bot @userinfobot
        jobStatus: ${{ job.status }}
        skipSuccess: false
